load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

package(default_visibility = ["//src/main:__subpackages__"])

kt_jvm_library(
    name = "file_processor",
    srcs = ["FileProcessor.kt"],
    resources = [
        "//src/main/resources/com/eleet/dragonconsole:font/dvsm.ttf",
    ],
)
