package(default_visibility = ["//src/main/java/com/eleet/dragonconsole:__subpackages__"])

java_library(
    name = "file_processor",
    srcs = ["FileProcessor.java"],
    resources = [
        "//src/main/resources/com/eleet/dragonconsole:font/dvsm.ttf",
    ],
)
