package(default_visibility = ["//src/main:__subpackages__"])

java_library(
    name = "input_controller",
    srcs = ["InputController.java"],
    deps = [
        "//src/main/kotlin/dev/bbuck/dragonconsole/text:input_string",
    ],
)
