exports_files(["font/dvsm.ttf"])

exports_files([
    "resources/ansi",
    "resources/colors",
    "resources/input",
    "resources/l_console",
    "resources/l_font",
    "resources/logo_b",
    "resources/logo_w",
])
